# Native Anthropic. This is the default every shell starts with.
set -e ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN ANTHROPIC_API_KEY ANTHROPIC_MODEL
set -e ANTHROPIC_DEFAULT_FABLE_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
set -e CLAUDE_CODE_SUBAGENT_MODEL CLAUDE_CODE_AUTO_MODE_MODEL
set -e PI_PROVIDER PI_MODEL
functions -e __llm_models
true
